config/routes.rb
Spree::Core::Engine.routes.draw do

  namespace :admin do
    resources :sites
  end
  match 'new_site' => 'sites#new', :as => :new_site
  resources :sites, :only => [:show]

  if Rails.env.development?
    mount Spree::UserMailer::Preview => 'mail_view'
  end
end

#map.namespace :admin do |admin|
#  admin.resources :sites
  ## admin.resources :taxonomies, :has_many => [:variants, :images, :product_properties] do |product|
#end  

app/models/spree/site.rb
class Spree::Site < ActiveRecord::Base
  cattr_accessor :unknown,:subdomain_regexp, :loading_fake_order_with_sample, :dalianshops_url
  has_many :taxonomies,:inverse_of =>:site,:dependent=>:destroy
  has_many :products,:inverse_of =>:site,:dependent=>:destroy
  has_many :orders,:inverse_of =>:site,:dependent=>:destroy
  has_many :users,:dependent=>:destroy, :class_name=>"Spree::User" #Spree.user_class.to_s
  #FIXME,:inverse_of =>:site, it cause  uninitialized constant Spree::Site::, 
  has_many :tax_categories,:inverse_of =>:site,:dependent=>:destroy
  
  has_many :shipping_categories,:dependent=>:destroy
  has_many :shipping_methods,:dependent=>:destroy
  has_many :prototypes,:dependent=>:destroy
  has_many :option_types,:dependent=>:destroy
  has_many :properties,:dependent=>:destroy
  has_many :payment_methods,:dependent=>:destroy
  has_many :assets,:dependent=>:destroy
  has_many :zones,:dependent=>:destroy
  has_many :state_changes,:dependent=>:destroy
  
  acts_as_nested_set
  accepts_nested_attributes_for :users
  
  #app_configuration require site_id
  self.unknown = Struct.new(:id).new(0)
  # it is load before create site table. self.new would trigger error "Table spree_sites' doesn't exist"
  # db/migrate/some_migration is using Spree::Product, it has default_scope using Site.current.id
  # so it require a default value.
  self.subdomain_regexp = /^([a-z0-9\-])*$/
  self.loading_fake_order_with_sample = false
  self.dalianshops_url = "www.dalianshops.com"
  validates_presence_of   :name
  validates :short_name, presence: true, length: 4..32, format: {with: subdomain_regexp} #, unless: "domain.blank?"
  validates :domain, uniqueness: true 
  attr_accessible :name, :domain, :short_name, :has_sample
  
  class << self
    def dalianshops
      find_by_domain dalianshops_url
    end
    
    def current
      ::Thread.current[:spree_site] || self.unknown 
    end
    
    def current=(some_site)
      ::Thread.current[:spree_site] = some_site      
    end
  end
  
  def dalianshops?
    self.domain == dalianshops_url
  end
  
  def unknown?
    !(self.id>0)
  end
  
  def load_sample(be_loading = true)
    require 'ffaker'
    # global talbes
    #   countries,states, zones, zone_members, roles #admin
    # activators,
    # tables belongs to site
    #   addresses -> user(site)
    #   configuration(site)
    #   log_entries(site)
    #   orders(site)->[state_changes,inventory_units,tokenized_permission]
    #   [properties(site), prototypes(site)] -> properties_prototypes
    #                    , option_types(site)] ->option_type_prototypes
    #         ->products(site)->variants(site?)->assets(site)
    #   payment_methods(site)->payments->adjustments 
    #   preference(site)
    #   tax_categories(site)-> tax_rates -> [shipping_methods, promotions,calculators]
    #   taxonomies(site) -> taxons(site) -> products_taxons(site?)
    #   user
    # to be confirm
    #   spree_tracker, state_changes
    #   return_authorizations
    #   mail_methods, pending_promotions, product_promotion_*
    # unused table
    #   credit_cars(site?), gateways(site?)
    #
    original_current_website, self.class.current = self.class.current, self 
    
    if be_loading!=true #
      self.orders.each{|order|
        order.state_changes.clear
        order.inventory_units.clear
        order.tokenized_permission.delete
        order.destroy
      }
      self.products.each{|product|
        product.variants.each{|variant| variant.inventory_units.clear}
      }
      self.products.clear
      self.properties.clear
      self.payment_methods.each{|pm| pm.delete}
      self.prototypes.clear
      self.option_types.clear
      self.shipping_categories.clear
      self.tax_categories.clear
      self.taxonomies.each{|taxonomy|
        taxonomy.root.destroy # remove taxons
        taxonomy.destroy
      }
      
      self.zones.each{|zone|
        zone.destroy
      }
      self.shipping_methods.clear
      
      #TODO fix taxons.taconomy_id
      self.users.find(:all,:include=>[:ship_address,:bill_address],:offset=>1, :order=>'id').each{|user|
        user.bill_address.destroy
        user.ship_address.destroy
        user.destroy
        } #skip first admin
      #shipping_method, calculator, creditcard, inventory_units, state_change,tokenized_permission
      #TODO remove image files
      self.assets.clear
      #FIXME seems it do not work 
      self.clear_preferences #remove preferences
      #TODO clear those tables
      # creditcarts,preferences
      self.state_changes.clear 
    else
      load_sample_products  
    end
    
   self.class.current = original_current_website
  end
  
  # current site'subdomain => short_name.dalianshops.com
  def subdomain
    ([self.short_name] + self.class.dalianshops.domain.split('.')[1..-1]).join('.')
  end
  
  private
  def load_sample_products
    file = Pathname.new(File.join(SpreeMultiSite::Config.seed_dir, 'samples', "seed.rb"))
Rails.logger.debug "start load #{file}"     
    load file
  end
  
  def load_sample_orders
    file = Pathname.new(File.join(SpreeMultiSite::Config.seed_dir, 'fake_order', "seed.rb"))
Rails.logger.debug "start load #{file}"     
    load file
  end
  
  def original_load_sample
    require 'ffaker'
    require 'erb'
    require 'spree_multi_site/custom_fixtures'
    # only load sample from one folder. by default is 'Rails.application.root/db/sample'
    # could override it by setting Spree::Config.data_path
    sample_dirs = ['sample']
    sample_dirs << 'fake_order' if self.class.loading_fake_order_with_sample                                               
    for sample_dir in sample_dirs    
      dir = File.join(SpreeMultiSite::Config.seed_dir,sample_dir)
  #Rails.logger.debug "load sample from dir=#{dir}"
      fixtures = ActiveSupport::OrderedHash.new
      ruby_files = ActiveSupport::OrderedHash.new
      Dir.glob(File.join(dir , '**/*.{yml,csv,rb}')).each do |fixture_file|
        ext = File.extname fixture_file
        if ext == ".rb"
          ruby_files[File.basename(fixture_file, '.*')] = fixture_file
        else
          fixtures[fixture_file.sub(dir, "")[1..-1]] = fixture_file
        end
      end
      # put eager loading model ahead, 
      fixture_indexes = ['sites',
        'shipping_categories','payment_methods',
        'properties','option_types','option_values', 
        'tax_categories','tax_rates','shipping_methods','promotions','calculators',
        'products','product_properties','product_option_types','variants','assets', 
        'taxonomies','taxons',
        'addresses','users','orders','line_items','shipments','adjustments']
      #{:a=>1, :b=>2, :c=>3}.sort => [[:a, 1], [:b, 2], [:c, 3]] 
      sorted_fixtures = fixtures.sort{|a,b|
        key1,key2  = a.first.sub(".yml", "").sub("spree/", ""), b.first.sub(".yml", "").sub("spree/", "")  #a.first is relative_path
  #puts "a=#{a.inspect},b=#{b.inspect} \n key1=#{key1}, key2=#{key2}, #{(fixture_indexes.index(key1)<=> fixture_indexes.index(key2)).to_i}"      
        i = (fixture_indexes.index(key1)<=> fixture_indexes.index(key2)).to_i
        i==0 ? -1 : i # key not in fixture_indexes should be placed ahead.
      }
      SpreeMultiSite::Fixtures.reset_cache
      sorted_fixtures.each do |relative_path , fixture_file|
        # load fixtures  
        # load_yml(dir,fixture_file)
  Rails.logger.debug "loading fixture_file=#{fixture_file}"
        if fixture_file =~/users.yml/ #user class may be legacy_user or user
          SpreeMultiSite::Fixtures.create_fixtures(dir, relative_path.sub(".yml", ""),{:spree_users=>Spree.user_class})
        else
          SpreeMultiSite::Fixtures.create_fixtures(dir, relative_path.sub(".yml", ""))            
        end
      end
  #puts "create habtm records"      
      SpreeMultiSite::Fixtures.create_habtm_records    
      ruby_files.sort.each do |fixture , ruby_file|
        # an invoke will only execute the task once
  Rails.logger.debug  "loading ruby #{ruby_file}"
        load ruby_file
      end
    end  #for sample_dir  
 
  end
    
end

app/controllers/spree/admin/sites_controller.rb
module Spree
  module Admin
    class SitesController< Spree::Admin::ResourceController
      #resource_controller
      self.create.after( :create_after )
      def new
        @user = @site.users.build
        super                    
      end
      
      def create
        @user = Spree.user_class.new(params[:user])
        @site.users << @user
        super
      end
      
      def create_after
        @site.users.first.roles << Role.find_by_name("admin") 
        # should not add  @site.name as suffix of role.name, User.admin require :name="admin"
        if @site.has_sample?
          @site.load_sample
          #@site.update_attributes!(:loading_sample=>true)
          # add job to load sample
          #Delayed::Job.enqueue SampleSeedJob.new( @site )
        end
      end
     
      private
      #def collection
      #  @collection ||= current_site.self_and_children
      #end
    end
  end
end

app/controllers/spree/sites_controller.rb
module Spree
    class SitesController< StoreController
      def new
        if request.get?
          @site = Site.new
          @user = @site.users.build
        else
          @site = Site.new(params[:site])
          @user = Spree.user_class.new(params[:user])
          @site.users << @user
          if @site.save
            @site.users.first.spree_roles << Spree::Role.find_by_name('admin')
            # should not add  @site.name as suffix of role.name, User.admin require :name="admin"
            if @site.has_sample?
              @site.load_sample
              #@site.update_attributes!(:loading_sample=>true)
              # add job to load sample
              #Delayed::Job.enqueue SampleSeedJob.new( @site )
            end 
            redirect_to site_path(@site)
          end
        end
      end
      
      def show
        @site = Site.find(params[:id])
        render :after_new
      end
           
    end
  
end

app/helpers/spree/admin/sites_helper.rb
module Spree
  module Admin::SitesHelper
    # spree's error_message_on would cause error in app/views/spree/admin/sites/_user.html.erb 
    # ActionView::Template::Error (`@site[users_attributes][0]' is not allowed as an instance variable name)
    # use this replace it original :error_message_on
    def customer_error_message_on(f,method)
      # it is copied from spree_core/app/helper/spree/admin/base_helper.rb #12 error_message_on
      obj = f.object
      if obj && obj.errors[method].present?
        errors = obj.errors[method].map { |err| h(err) }.join('<br />').html_safe
        content_tag(:span, errors, :class => 'formError')
      else
        ''
      end 
    end
  end
end

app/views/spree/admin/sites/_form.html.erb
<div data-hook="admin_site_form_fields">
  <div class="clearfix">
    <div class="left" data-hook="admin_site_form_left">
      <%= f.field_container :name do %>
        <%= f.label :name, t(:site_name) %> <span class="required">*</span><br />
        <%= f.text_field :name, :class => 'fullwidth title' %>
        <%= f.error_message_on :name %>
      <% end %>
      <%= f.field_container :domain do %>
        <%= f.label :domain, t(:site_domain) %> <br />
        <%= f.text_field :domain, :class => 'fullwidth title' %>
        <%= f.error_message_on :domain %>
      <% end %>
      <%= f.field_container :short_name do %>
        <%= f.label :short_name, t(:site_short_name) %> <span class="required">*</span><br />
        <%= f.text_field :short_name, :class => 'fullwidth title' %>
        <%= f.error_message_on :short_name %>
      <% end %>
      <%= f.field_container :layout do %>
        <%= f.label :layout, t(:site_layout) %> <br />
        <%= f.text_field :layout, :class => 'fullwidth title' %>
        <%= f.error_message_on :layout %>
      <% end %>

      <%= f.field_container :has_sample do %>
        <%= f.label :has_sample, t(:site_has_sample) %> <br />
        <%= f.check_box :has_sample, :class => 'fullwidth title' %>
        <%= f.error_message_on :has_sample %>
      <% end %>
      <% if @site.new_record? %>
        
        <%= render :partial => 'spree/admin/sites/user', :locals => { :user => @user } %>
            
      <% end %>
    </div>
  </div>
</div>

app/views/spree/admin/sites/_user.html.erb
<div data-hook="admin_user_form_fields">
  <p>
    <%= label :user, :email, t(:user_email) %><span class="required">*</span><br />
    <%= email_field :user, :email %>
    <%= error_message_on  :user,:email %>
  </p>

  <p>
    <%= label :user,:password, t(:password,:scope=>['activerecord','attributes','user']) %><span class="required">*</span><br />
    <%= password_field :user,:password %>
    <%= error_message_on :user,:password %>
  </p>

  <p>
    <%= label :user,:password_confirmation, t(:confirm_password) %><span class="required">*</span><br />
    <%= password_field :user,:password_confirmation %>
    <%= error_message_on :user,:password_confirmation %>
  </p>
</div>

app/views/spree/admin/sites/edit.html.erb
<h1><%= t("editing_site") %></h1>
<p id="ajax_error" class="errorExplanation" style="display:none;"></p>
<%= form_for [:admin, @site] do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
    <p class="form-buttons">
      <%= button t(:update) %> <%= t(:or) %> <%= link_to t(:cancel), admin_sites_path %>
    </p>
<% end %>

app/views/spree/admin/sites/index.html.erb
<h1><%= t("listing_sites") %></h1>

<table>
  <tr>
    <td valign="top">
      <table class="admin-report">
        <thead>
          <th><%= t("site_name") %></th>
          <th><%= t("site_domain") %></th>
          <th><%= t("site_layout") %></th>
          <th><%= t("site_loading_sample") %></th>
          <th><%= t("action") %></th>
        </thead>
        <tbody>
          <%- @sites.each do |site|%>
          <tr>
            <td width="116px"><%=link_to site.name, object_url(site) %></td>
            <td width="116px"><%=link_to site.domain, object_url(site) %></td>
            <td width="117px"><%=link_to (site.layout || "N/A"), object_url(site) %></td>
            <td width="117px"><%=link_to (site.loading_sample? ? t(:yes) : t(:no)), object_url(site) %></td>
            <td>
            	<%=link_to t('edit'), edit_object_url(site) %> |
            	<%=link_to t('destroy'), object_url(site), :confirm => t('are_you_sure'), :method => :delete %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </td>
    <td valign="top">
      <% form_for :filter, :url => admin_sites_url, :html => { :method => :get } do |f| %>
        <div id="search-col">
          <table class="admin-search">
            <thead>
              <tr>
                <th colspan="2"><%= t("site_details") %></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= t("name") %></td>
                <td>
                  <%= f.text_field :name, :size=>18 %>
                </td>
              </tr>
            </tbody>
          </table>
          <%=submit_tag t("search") %>
        </div>
      <% end %>
    </td>
  </tr>
</table>
            


<%= link_to t('new_site'), new_object_url %>

app/views/spree/admin/sites/new.html.erb
<h1><%= t("new_site") %></h1>
<br/>
<%= form_for [:admin, @site]  do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <p class="form-buttons" data-hook="buttons">
    <%= button t(:create) %>
  </p>
<% end %>
<br/>
<%= link_to t('back'), collection_url %>

app/views/spree/admin/sites/show.html.erb
<h1><%= t("site_account") %></h1>        
<br/>
<table>
  <tr>
    <td><%= t("site_name") %>: &nbsp;</td>
    <td>
      <%= @site.name %>
    </td>
  </tr>  
  <tr>
    <td><%= t("site_domain") %>: &nbsp;</td>
    <td>
      <%= @site.domain %>
    </td>
  </tr>
  <tr>
    <td><%= t("site_layout") %>: &nbsp;</td>
    <td>
      <%= @site.layout %>
    </td>
  </tr>
</table>
<br/>
<%= link_to_edit @site, :class => 'edit_site' %> <%= t(:or) %>
  <%= link_to t(:back), collection_url %>